// src/editor/widget/DisplayUtility/DisplayUtility.tsx
import en from "./string/en.json";
import i18next from "i18next";
import * as styles from "./DisplayUtility.module.scss";
import ImageIconSvg from "@res/svg/small/image.svg";
// import MotionIconSvg from "@res/svg/small/motion.svg";

import {/*Dialog,*/ Icon, Modal} from "@src/utility/view";
import {JSX, Show, createMemo} from "solid-js";
// import {MotionBrowser} from "@src/asset/widget";
import {Entity, Visual} from "@src/entity/type";
// import {Prop, Motion} from "@src/asset/type";
import {useViewerContext} from "@src/viewer/context";
import {useEditorContext} from "@src/editor/context";
import {Section, Widget} from "@src/editor/widget/UtilityBar/widget";
import {PropBrowser} from "@src/asset/widget";

i18next.addResourceBundle("en", "entity", {AppearanceSection: en}, true, true);

type Props = {
    uid: string;
};

export function DisplayUtility(props: Props): JSX.Element {
    const {storage, session} = useEditorContext();
    const {path} = useViewerContext();

    const entityMemo = createMemo(
        () => session.selected || {} as Entity
    );

    function isVisual(entity: Entity | Visual): entity is Visual {
        return "propId" in entity;
    }

    const propSrc = createMemo((): string | undefined => {
        const entity = entityMemo();

        if (!isVisual(entity)) return undefined;

        const propId = "propId" in entity ? entity.propId : undefined;

        if (!propId) return undefined;

        const prop = storage.data.asset.select(propId);

        if (!prop) return undefined;

        const src = path + prop.path;

        return src;
    });

    // const selectedProp = createMemo(() => {
    //     const propId = entityMemo().propId;
    //     return propId ? [propId] : [];
    // });

    const propBrowserDialog = new Modal();
    propBrowserDialog.render(
        <PropBrowser
            // selected={selectedProp()}
            onSelect={(ids: number[]) => {
                storage.data.entity
                    .update<Entity & {propId: number}>(
                        entityMemo().id,
                        {propId: ids[0]}
                    );
                propBrowserDialog.hide();
            }}
        />
    );

    // const motionClass = createMemo((): string | undefined => {
    //     const motionId = entityMemo().motionId;

    //     if (!motionId) return undefined;

    //     const motion = storage.data.asset
    //         .select<Motion>(motionId);

    //     if (!motion) return undefined;

    //     return motion.class;
    // });

    // const classList = createMemo(() => {
    //     return {[motionClass() || ""]: Boolean(motionClass())};
    // });

    // const selectedMotion = createMemo(() => {
    //     const {motionId} = entityMemo();
    //     return motionId ? [motionId] : [];
    // });

    // const motionBrowserDialog = new Modal();
    // motionBrowserDialog.render(
    //     <Dialog
    //         class={styles.AssetBrowserDialog}
    //         onClose={() => motionBrowserDialog.hide()}
    //     >
    //         <MotionBrowser
    //             selected={selectedMotion()}
    //             onSelect={(ids: number[]) => {
    //                 storage.data.entity
    //                     .update<Entity & {motionId: number}>(
    //                         entityMemo().id,
    //                         {motionId: ids[0]}
    //                     );
    //                 motionBrowserDialog.hide();
    //             }}
    //         />
    //     </Dialog>
    // );

    return (
        <Widget
            class={styles.DisplayUtility}
            uid={props.uid}
            title="Display"
        >
            <Show when={isVisual(entityMemo())}>
                <Section uid="mwem" title="Prop">
                    <Show
                        when={propSrc()}
                        fallback={(
                            <Icon
                                class={styles.Preview}
                                //classList={classList()}
                                svg={ImageIconSvg}
                                onClick={() => propBrowserDialog.show()}
                            />
                        )}
                    >
                        <img
                            class={styles.Preview}
                            src={propSrc()}
                            draggable={false}
                            onPointerDown={() => {
                                propBrowserDialog.show();
                            }}
                        />
                    </Show>
                </Section>
            </Show>
            {/* <div class={styles.Toolbar}>
                <Button
                    icon={ImageIconSvg}
                    onClick={() => propBrowserDialog.show()}
                />
                <Button
                    icon={MotionIconSvg}
                    onClick={() => motionBrowserDialog.show()}
                />
            </div>

             */}

        </Widget>
    );
}

// src/editor/view/utility/DisplayUtility.vue
<script setup lang="ts">

// import {MotionBrowser} from "@src/editor/view";
import type {Entity, Visual} from "@src/core/type";
// import {Prop, Motion} from "@src/core/type";
import {useViewerContext} from "@src/viewer/context";
import {useScopeContext, useEditorContext} from "@src/editor/context";
import {Section, Widget} from "@src/editor/view/UtilityBar";
import {computed} from "vue";
// import {PropBrowser} from "@src/editor/view";

const {storage, session} = useEditorContext();
const {path} = useViewerContext();

// const entity = computed(
// 	() => session.selected || {} as Entity
// );

// function isVisual(entity: Entity | Visual): entity is Visual {
// 	return "propId" in entity;
// }

// const propSrc = computed((): string | undefined => {
// 	if (!isVisual(entity.value)) return undefined;

// 	const propId = "propId" in entity.value ? entity.value.propId : undefined;

// 	if (!propId) return undefined;

// 	const prop = storage.data.asset.select(propId);

// 	if (!prop) return undefined;

// 	const src = path + prop.path;

// 	return src;
// });

// const selectedProp = createMemo(() => {
//     const propId = entityMemo().propId;
//     return propId ? [propId] : [];
// });

// const propBrowserDialog = new Modal();
// propBrowserDialog.render(
//     <PropBrowser
//         // selected={selectedProp()}
//         onSelect={(ids: number[]) => {
//             storage.entity
//                 .update<Entity & {propId: number}>(
//                     entityMemo().id,
//                     {propId: ids[0]}
//                 );
//             propBrowserDialog.hide();
//         }}
//     />
// );

// const motionClass = createMemo((): string | undefined => {
//     const motionId = entityMemo().motionId;

//     if (!motionId) return undefined;

//     const motion = storage.data.asset
//         .select<Motion>(motionId);

//     if (!motion) return undefined;

//     return motion.class;
// });

// const classList = createMemo(() => {
//     return {[motionClass() || ""]: Boolean(motionClass())};
// });

// const selectedMotion = createMemo(() => {
//     const {motionId} = entityMemo();
//     return motionId ? [motionId] : [];
// });

// const motionBrowserDialog = new Modal();
// motionBrowserDialog.render(
//     <Dialog
//         class={styles.AssetBrowserDialog}
//         onClose={() => motionBrowserDialog.hide()}
//     >
//         <MotionBrowser
//             selected={selectedMotion()}
//             onSelect={(ids: number[]) => {
//                 storage.entity
//                     .update<Entity & {motionId: number}>(
//                         entityMemo().id,
//                         {motionId: ids[0]}
//                     );
//                 motionBrowserDialog.hide();
//             }}
//         />
//     </Dialog>
// );
useScopeContext("DisplayUtility");
</script>

<template>
<Widget
	class="DisplayUtility"
	title="Display"
>
	<!-- <Section
		v-if="isVisual(entity)"
		title="Prop"
	>
		<img
			v-if="propSrc"
			class="Preview"
			:src="propSrc"
			:draggable="false"
			@pointerDown="() => {
				// propBrowserDialog.show();
			}"
		>
	</Section> -->
	<div class="Toolbar">
		<!-- <Button
			:icon="ImageIconSvg"
		/>
		<Button
			:icon="MotionIconSvg"
		/> -->
	</div>

	*/}
</Widget>
</template>

<style lang="scss" scoped>
.DisplayUtility {
    .Toolbar {
        display: flex;
        flex-direction: row;
    }

    .Preview {
        align-self: center;
        width: 64px;
        min-height: 64px;
        height: auto;
        cursor: pointer;
    }
}

.AssetBrowserDialog {
    width: 60%;
    height: 60%;
}
</style>
