// src/editor/widget/LayerUtility/LayerUtility.tsx
import * as styles from "./LayerUtility.module.scss";
import {createMemo, For, JSXElement, on} from "solid-js";
import {Widget} from "@src/editor/widget/UtilityBar/widget";
import {EntityKind} from "@src/entity/enum";
import {useEditorContext} from "@src/editor/context";
import {Layer} from "@src/entity/type";

type Props = {
    uid: string;
};

export function LayerUtility(props: Props): JSXElement {
    const {storage, session, setSession} = useEditorContext();

    const layers = createMemo(on(storage.reloaded, () =>
        storage.data.entity
            .filter<Layer>({kind: EntityKind.Layer})
    ));

    return (
        <Widget uid={props.uid} title="Layers">
            <div class={styles.Layers}>
                <For each={layers()}>
                    {layer =>
                        <div
                            class={styles.Layer}
                            classList={{
                                [styles.Selected]: session.layer == layer,
                            }}
                            onClick={() => setSession({layer})}
                        >
                            Layer id:{layer.id}
                            {String(session.layer == layer)}
                        </div>
                    }
                </For>
            </div>
        </Widget>
    );
}

// src/editor/view/utility/LayerUtility.vue
<script setup lang="ts">
import {Widget} from "@src/editor/view/UtilityBar";
import {EntityKind} from "@src/core/enum";
import {useScopeContext, useEditorContext} from "@src/editor/context";
import type {Layer} from "@src/core/type";
import {computed} from "vue";

const {storage, session} = useEditorContext();

const layers = computed(() =>
	storage.entity
		.filter<Layer>({kind: EntityKind.Layer})
);

useScopeContext("LayerUtility");
</script>

<template>
<Widget title="Layers">
	<div class="Layers">
		<div
			v-for="(layer, index) in layers"
			:key="index"
			class="Layer"
			:class="{'Selected': session.layer == layer}"
			@click="() => session.layer = layer"
		>
			Layer id:{{ layer.id }}
			{{ String(session.layer == layer) }}
		</div>
	</div>
</Widget>
</template>

<style lang="scss" scoped>
.Layers {
	overflow-y: scroll;
	overflow-x: scroll;

	.Layer {
		cursor: pointer;
		color: red;
	}

	.Selected {
		color: blue;
	}
}
</style>
