// src/editor/view/utility/EntityUtility.vue
<script setup lang="ts">

import {useScopeContext, useEditorContext} from "@src/editor/context";
import {type Entity, isSize, isSpatial, type Size, type Spatial} from "@src/core/type";
import {Widget, Section, Field} from "@src/editor/view/UtilityBar";
import {computed} from "vue";
import Scope from "../Scope.vue";

const {storage, session} = useEditorContext();

const entity = computed(() => session.selected || {} as Entity);

const spatial = computed(() => {
	return isSpatial(entity.value)
		? entity as unknown as Entity & Spatial
		: undefined;
});

const size = computed(() => {
	return isSize(entity.value) ? entity : undefined;
});

function handleXChange(event: Event): void {
	const target = event.target as HTMLInputElement;
	storage.entity.update<Entity & Spatial>(
		entity.value.id,
		{x: Number(target.value)}
	);
}

function handleYChange(event: Event): void {
	const target = event.target as HTMLInputElement;
	storage.entity.update<Entity & Spatial>(
		entity.value.id,
		{y: Number(target.value)}
	);
}

function handleWidthChange(event: Event): void {
	const target = event.target as HTMLInputElement;
	storage.entity.update<Entity & Size>(
		entity.value.id,
		{w: Number(target.value)}
	);
}

function handleHeightChange(event: Event): void {
	const target = event.target as HTMLInputElement;
	storage.entity.update<Entity & Size>(
		entity.value.id,
		{h: Number(target.value)}
	);
}

const labels = {
	id: "id",
	kind: "kind",
	x: "x",
	y: "y",
	width: "width",
	height: "height",
};

useScopeContext("EntityUtility");

</script>

<template>
<Scope name="EntityUtility">
	<Widget title="Entity">
		<Scope name="SystemSection">
			<Section title="system">
				<Field
					name="id"
					:label="labels.id"
					:value="String(entity?.id)"
					readonly
				/>
				<Field
					name="kind"
					:label="labels.kind"
					:value="String(entity.kind)"
					readonly
				/>
			</Section>
		</Scope>

		<Scope
			v-if="spatial"
			name="PositionSection"
		>
			<Section title="size">
				<Field
					name="x"
					type="number"
					:label="labels.x"
					:value="String(spatial?.x)"
					@change="handleXChange"
				/>
				<Field
					label="{labels.y}"
					type="number"
					name="y"
					value="{String(spatialMemo()?.y)}"
					on-change="{handleYChange}"
				/>
			</Section>
		</Scope>
		<Scope
			v-if="size"
			name="SizeSection"
		>
			<Section title="size">
				<Field
					label="{labels.width}"
					type="number"
					name="width"
					value="{String(sizeMemo()?.w)}"
					on-change="{handleWidthChange}"
				/>
				<Field
					label="{labels.height}"
					type="number"
					name="height"
					value="{String(sizeMemo()?.h)}"
					on-change="{handleHeightChange}"
				/>
			</Section>
		</Scope>
	</Widget>
</Scope>
</template>

// src/editor/widget/EntityUtility/EntityUtility.tsx
import en from "./string/en.json";
import i18next from "i18next";

import {JSX, Show, createMemo} from "solid-js";
import {useEditorContext} from "@src/editor/context";
import {Field, Input} from "@src/utility/view";
import {Entity, isSize, isSpatial, Size, Spatial} from "@src/entity/type";
import {Widget, Section} from "@src/editor/widget/UtilityBar/widget";

i18next.addResourceBundle("en", "tool", {Entity: en}, true, true);

type Props = {
    uid: string;
};

export function EntityUtility(props: Props): JSX.Element {
    const {storage, session} = useEditorContext();

    const entityMemo = createMemo(
        () => session.selected || {} as Entity
    );

    const spatialMemo = createMemo(() => {
        const entity = entityMemo();
        return isSpatial(entity) ? entity : undefined;
    });

    const sizeMemo = createMemo(() => {
        const entity = entityMemo();
        return isSize(entity) ? entity : undefined;
    });

    function handleXChange(event: Event): void {
        const target = event.target as HTMLInputElement;
        storage.data.entity.update<Entity & Spatial>(
            entityMemo().id,
            {x: Number(target.value)}
        );
    }

    function handleYChange(event: Event): void {
        const target = event.target as HTMLInputElement;
        storage.data.entity.update<Entity & Spatial>(
            entityMemo().id,
            {y: Number(target.value)}
        );
    }

    function handleWidthChange(event: Event): void {
        const target = event.target as HTMLInputElement;
        storage.data.entity.update<Entity & Size>(
            entityMemo().id,
            {width: Number(target.value)}
        );
    }

    function handleHeightChange(event: Event): void {
        const target = event.target as HTMLInputElement;
        storage.data.entity.update<Entity & Size>(
            entityMemo().id,
            {height: Number(target.value)}
        );
    }

    const labels = {
        id: i18next.t(
            "tool:Entity.idLabel",
            {postProcess: ["capitalize"]}
        ),
        kind: i18next.t(
            "tool:Entity.kindLabel",
            {postProcess: ["capitalize"]}
        ),
        x: i18next.t(
            "tool:Entity.xLabel",
            {postProcess: ["capitalize"]}
        ),
        y: i18next.t(
            "tool:Entity.yLabel",
            {postProcess: ["capitalize"]}
        ),
        width: i18next.t(
            "tool:Entity.widthLabel",
            {postProcess: ["capitalize"]}
        ),
        height: i18next.t(
            "tool:Entity.heightLabel",
            {postProcess: ["capitalize"]}
        ),
    };

    return (
        <Widget uid={props.uid} title="Entity">
            <Section uid="vadf" title="system">
                <Field>
                    <label for="id">{labels.id}</label>
                    <Input
                        name="id"
                        value={String(entityMemo()?.id)}
                        readonly
                    />
                </Field>
                <Field>
                    <label for="kind">{labels.kind}</label>
                    <Input
                        name="kind"
                        value={String(entityMemo()?.kind)}
                        readonly
                    />
                </Field>
            </Section>
            <Show when={spatialMemo()} fallback={<></>}>
                <Section uid="vads" title="position">
                    <Field>
                        <label for="x">{labels.x}</label>
                        <Input
                            type="number"
                            name="x"
                            value={String(spatialMemo()?.x)}
                            onChange={handleXChange}
                        />
                    </Field>
                    <Field>
                        <label for="y">{labels.y}</label>
                        <Input
                            type="number"
                            name="y"
                            value={String(spatialMemo()?.y)}
                            onChange={handleYChange}
                        />
                    </Field>
                </Section>
            </Show>
            <Show when={sizeMemo()} fallback={<></>}>
                <Section uid="whfl" title="size">
                    <Field>
                        <label for="width">{labels.width}</label>
                        <Input
                            type="number"
                            name="width"
                            value={String(sizeMemo()?.width)}
                            onChange={handleWidthChange}
                        />
                    </Field>
                    <Field>
                        <label for="height">{labels.height}</label>
                        <Input
                            type="number"
                            name="height"
                            value={String(sizeMemo()?.height)}
                            onChange={handleHeightChange}
                        />
                    </Field>
                </Section>
            </Show>
        </Widget>
    );
}
