// src/viewer/view/TileView.vue
<script setup lang="ts">

import {computed, inject} from "vue";
import type {Tile} from "@src/core/type";
import type {Storage} from "@src/core/controller";

type Props = {
	entity: Tile;
};

const props = defineProps<Props>();

const viewerContext = inject<{
	storage: Storage;
	path: string;
}>("viewerContext");

if (!viewerContext) {
	throw new Error("ViewerContext is not provided");
}

const {storage, path} = viewerContext;

const tileStyle = computed(() => {
	return {
		transform: `translate3d(${props.entity.x}px, ${props.entity.y}px, 0)`,
	};
});

const src = computed((): string => {
	const imageId = props.entity.imageId;

	if (!imageId) {
		return "";
	}
	else {
		const tile = storage.data.asset.select(imageId);

		if (!tile) throw new Error("Tile asset not found");

		return path + tile.path;
	}
});
</script>

<template>
<img
	class="Tile"
	:src="src"
	:style="tileStyle"
	:draggable="false"
>
</template>

<style scoped lang="scss">
.Tile {
  position: absolute;
  top: 0;
  left: 0;

  user-select: none;
  image-rendering: optimizeQuality;
}
</style>

// src/entity/widget/TileView/TileView.tsx
import * as styles from "./TileView.module.scss";
import {Accessor, JSX, createMemo} from "solid-js";
import {Tile} from "@src/entity/type";
import {useSharedContext} from "@src/shared/context";
import {useViewerContext} from "@src/viewer/context";

type Props = {
    entity: Accessor<Tile>;
};

export function TileView({entity}: Props): JSX.Element {
    const sharedContext = useSharedContext();
    const viewerContext = useViewerContext();

    const style = createMemo((): JSX.CSSProperties => {
        return {transform: `translate3d(${entity().x}px, ${entity().y}px, 0)`};
    });

    const src = createMemo((): string => {
        const imageId = entity().imageId;

        if (!imageId) {
            return "";
        }
        else {
            const tile = sharedContext.database.data.asset.select(imageId);

            if (!tile) throw new Error();

            const src = viewerContext.path + tile.path;

            return src;
        }
    });

    return (
        <img
            class={styles.Tile}
            src={src()}
            style={style()}
            draggable={false}
        />
    );
}
