// src/feature/asset/view/AssetBrowser/AssetBrowser.tsx
import PlusIconSvg from "@res/svg/plus.svg";
import SaltireIconSvg from "@res/svg/saltire.svg";
import * as styles from "./AssetBrowser.module.scss";
import en from "./string/en.json";

import {For, JSX, Show, createEffect, createMemo, createSignal} from "solid-js";
import i18next from "i18next";
import {Button} from "@shared/view";
import {useStoreContext} from "@feature/store/context";
import {Asset} from "@feature/asset/type";

i18next.addResourceBundle("en", "asset", {"AssetBrowser": en}, true, true);

type Props = {
    type?: number;
    multiple?: boolean;
    selected?: number[];
    onCreate?: () => void;
    onSelect?: (ids: number[]) => void;
    onDelete?: (ids: number[]) => void;
};

export function AssetBrowser(props: Props): JSX.Element {
    const storeContext = useStoreContext();

    const assets = createMemo(() => {
        return props.type
            ? storeContext.store.asset
                .selectByParams<Asset>({assetTypeId: props.type})
            : storeContext.store.asset
                .selectAll<Asset>();
    });

    const [selected, setSelected] = createSignal<number[]>([] as number[]);

    createEffect(() => {
        setSelected(props.selected ?? []);
    });

    return (
        <div class={styles.AssetBrowser}>
            <div class={styles.Assets}>
                <table>
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>name</th>
                            <th>media</th>
                            <th>size (in kb)</th>
                            <th>
                                <Show when={props.onCreate}>
                                    <Button
                                        icon={PlusIconSvg}
                                        onClick={() => {
                                            if (props.onCreate) {
                                                props.onCreate();
                                            }
                                        }}
                                    />
                                </Show>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <For each={assets()}>
                            {(asset) =>
                                <tr
                                    classList={{
                                        [styles.Selected]: selected()
                                            .includes(asset.id),
                                    }}
                                    onClick={(event: MouseEvent) => {
                                        if (props.multiple && event.shiftKey) {
                                            setSelected((prev) => {
                                                return !prev.includes(asset.id)
                                                    ?  [...prev, asset.id]
                                                    : prev;
                                            });
                                        }
                                        else {
                                            setSelected([asset.id]);
                                        }
                                    }}
                                    onDblClick={() => {
                                        setSelected([asset.id]);
                                        if (props.onSelect) {
                                            props.onSelect(selected());
                                        }
                                    }}
                                >
                                    <td>{asset.id}</td>
                                    <td>{asset.name}</td>
                                    <td>{asset.media}</td>
                                    <td>{Math.floor(asset.size / 1024)}</td>
                                    <td>
                                        <Show when={props.onDelete}>
                                            <Button
                                                icon={SaltireIconSvg}
                                                onClick={() => {
                                                    if (props.onDelete) {
                                                        props.onDelete(
                                                            [asset.id]
                                                        );
                                                    }
                                                }}
                                            />
                                        </Show>
                                    </td>
                                </tr>
                            }
                        </For>
                    </tbody>
                </table>
            </div>
            <button
                onClick={() => {
                    if (props.onSelect) props.onSelect(selected());
                }}
            >
                select
            </button>
        </div>
    );
}

// src/editor/view/component/AssetBrowser.vue
<script setup lang="ts">
import type {Asset} from "@src/core/type/asset";
import type {AssetKind} from "@src/core/enum";
import {computed} from "vue";
import {useCoreContext} from "@src/core/view/context";

const props = defineProps<{
	type?: AssetKind;
	multiple?: boolean;
	selected?: number[];
	onCreate?: () => void;
	onSelect?: (ids: number[]) => void;
	onDelete?: (ids: number[]) => void;
}>();

const {storage} = useCoreContext();

const assets = computed(() => {
	return props.type
		? storage.asset
			.selectByParams<Asset>({assetTypeId: props.type})
		: storage.asset
			.selectAll<Asset>();
});

// const [selected, setSelected] = createSignal<number[]>([] as number[]);

// createEffect(() => {
// 	setSelected(props.selected ?? []);
// });

</script>

<template>
<div class="AssetBrowser">
	<div class="Assets">
		<table>
			<thead>
				<tr>
					<th>id</th>
					<th>name</th>
					<th>media</th>
					<th>size (in kb)</th>
					<th>
						<Button>
							Добавить
						</Button>>
					</th>
				</tr>
			</thead>
			<tbody>
				<!-- <tr>
						<td>{asset.id}</td>
						<td>{asset.name}</td>
						<td>{asset.mime}</td>
						<td>{Math.floor(asset.size / 1024)}</td>
						<td>
							<Show when="{props.onDelete}">
								<Button
									icon="{SaltireIconSvg}"
									on-click="{()"
									=
								>
									{
									if (props.onDelete) {
									props.onDelete(
									[asset.id]
									);
									}
									}}
									/>
								</button>
							</Show>
						</td>
					</tr> -->
			</tbody>
		</table>
	</div>
	<Button />
</div>
</template>

<style lang="scss" scoped>
.AssetBrowser {
    width: 100%;
    height: 100%;

    display: flex;
    flex-direction: column;
    gap: 16px;

    .Assets {
        border-collapse: collapse;
        overflow: scroll;

        button {
            width: 24px;
            height: 24px;
        }

        table {
            width: 100%;

            thead {
                position: sticky;
                top: 0;
            }

            tr {
                cursor: pointer;
                text-align: center;
                user-select: none;

                &.Selected {
                    background-color: lemonchiffon;
                }

                th, td {
                    padding: 8px;
                }
            }

        }
    }
}
</style>
