// src/editor/view/utility-bar/widget/CreateUtility.vue
<script setup lang="ts">
import {Widget} from "@src/editor/view/utility-bar";
import {Button, Icon} from "@src/core/view";
import {InputMode} from "@src/editor/enum";
import {useEditorContext} from "@src/editor/context";
import {Scope} from "@src/editor/view";
import {IconName} from "@src/core/enum";

const {session} = useEditorContext();
const buttons = [
	{
		input: InputMode.ImageCreate,
		icon: IconName.Image,
		label: "image",
	},
	{
		input: InputMode.MarkerCreate,
		icon: IconName.Marker,
		label: "marker",
	},
	// {input: InputMode.DecorCreate, icon: IconName.Decor},
	// {input: InputMode.AreaCreate, icon: IconName.Polygon},
];

</script>

<template>
<Scope name="CreateUtility">
	<Widget
		title="Create entity"
		class="Widget"
	>
		<div class="Panel">
			<Button
				v-for="(button, index) in buttons"
				:key="index"
				:pressed="session.inputMode == button.input"
				:icon="button.icon"
				@click="() => session.inputMode = button.input"
			>
				<Icon
					class="Icon"
					:name="button.icon"
				/>
				<label>
					{{ button.label }}
				</label>
			</Button>
		</div>
	</Widget>
</Scope>
</template>

<style lang="scss" scoped>
.Panel {
    display: flex;
    flex-direction: column;
	justify-content: left;
	gap: 8px;
	width: fit-content;

	.Button {
		display: flex;
		align-items: center;
		gap: 8px;
		width: fit-content;

		.Icon {
			height: 42px;
			width: 42px;
			padding: 8px;

			border: 1px solid var(--gray-60);
			border-radius: 8px;
		}
	}
}
</style>

// src/editor/widget/utility/CreateUtility/CreateUtility.tsx
import * as styles from "./CreateUtility.module.scss";
import MarkerIconSvg from "@res/svg/small/marker.svg";
import ImageIconSvg from "@res/svg/small/image.svg";
import DecorIconSvg from "@res/svg/small/decor.svg";
import PolygonIconSvg from "@res/svg/small/polygon.svg";
import {Widget, Button} from "@src/editor/widget/UtilityBar/widget";
import {For, JSX} from "solid-js";
import {InputMode} from "@src/editor/enum";
import {useEditorContext} from "@src/editor/context";

type Props = {
    uid: string;
};

export function CreateUtility(props: Props): JSX.Element {
    const {session, setSession} = useEditorContext();
    const buttons: {icon: string; input: InputMode}[] = [
        {icon: ImageIconSvg, input: InputMode.ImageCreate},
        {icon: MarkerIconSvg, input: InputMode.MarkerCreate},
        {icon: DecorIconSvg, input: InputMode.DecorCreate},
        {icon: PolygonIconSvg, input: InputMode.AreaCreate},
    ];

    return (
        <Widget
            title="Create entity"
            class={styles.Widget}
            uid={props.uid}
        >
            <For each={buttons}>
                {(button) =>
                    <Button
                        pressed={session.inputMode == button.input}
                        icon={button.icon}
                        onClick={() => setSession({inputMode: button.input})}
                    />
                }
            </For>
        </Widget>
    );
}
