// src/editor/widget/UtilityBar/widget/Field/Field.tsx
import {JSX} from "solid-js";
import * as styles from "./Field.module.scss";

type Props = {
    label: string;
    name: string;
    type: string;
    value?: string;
    accept?: string;
    step?: string;
    readonly?: boolean;
    required?: boolean;
    onKeyDown?: () => void;
    onChange?: () => void;
};

export function Field(props: Props): JSX.Element {
    return (
        <div class={styles.Field}>
            <label
                class={styles.Label}
                for={props.name}
            >
                {props.label}
            </label>
            <input
                class={styles.Input}
                type={props.type}
                name={props.name}
                // value={props.value || undefined}
                step={props.step}
                onKeyDown={props.onKeyDown}
                onChange={props.onChange}
                readonly={props.readonly}
                required={props.required}
            />
        </div>
    );
}

// src/editor/view/UtilityBar/Field.vue
<script setup lang="ts">
import {Field} from "@src/core/view";

defineProps<{
	label: string;
	name: string;
	type?: string;
	value?: string;
	accept?: string;
	step?: string;
	readonly?: boolean;
	required?: boolean;
}>();

</script>

<template>
<Field
	v-bind="$props"
	:class-list="$style"
/>
</template>

<style lang="scss" module>
.Field {
    gap: 16px;

    .Label {
        /**/
    }

    .Input {
        /**/
    }
}
</style>
