// src/editor/view/utility-bar/widget/InitUtility.vue
<script setup lang="ts">
import {initProject} from "@src/editor/service";
import {Widget, Field} from "@src/editor/view/utility-bar";
import {useEditorContext} from "@src/editor/context";
import {useViewerContext} from "@src/viewer/context";
import {Scope} from "@src/editor/view";
import {ActivityKind} from "@src/editor/enum";
import {SystemActivity} from "@src/editor/type/activity";

const {storage, session} = useEditorContext();
const {viewport, loop: engine} = useViewerContext();

function projectCreate(event: SubmitEvent): void {
	event.preventDefault();

	const form = event.target as HTMLFormElement;
	const formData = new FormData(form);
	form.reset();

	const name = String(formData.get("name"));
	const width = Number(formData.get("width"));
	const height = Number(formData.get("height"));

	initProject(storage, {name, width, height});

	viewport.setCanvas({
		x: 0,
		y: 0,
		w: storage.config.width,
		h: storage.config.height,
	});

	engine.requestUpdate();

	session.value.activity = {kind: ActivityKind.System};
}

const strings = {
	"nameField": "name",
	"backgroundField": "background",
	"create": "create",
	"cancel": "cancel",
	"width": "width",
	"height": "height",
};

</script>

<template>
<Scope name="InitTool">
	<Widget title="Init">
		<form
			class="InitTool"
			@submit="projectCreate"
		>
			<Field
				:label="strings.nameField"
				name="name"
				type="text"
				required
			/>
			<Field
				:label="strings.width"
				name="width"
				type="number"
				required
			/>
			<Field
				:label="strings.height"
				name="height"
				type="number"
				required
			/>
			<input
				type="submit"
				:value="strings.create"
			>
		</form>
	</Widget>
</Scope>
</template>

<style lang="scss" scoped>
.InitTool {
    display: flex;
    flex-direction: column;
    gap: 16px;
}
</style>

// src/editor/widget/utility/InitUtility/InitUtility.tsx
import en from "./string/en.json";
import * as styles from "./InitUtility.module.scss";
import i18next from "i18next";
import {JSX} from "solid-js";
import {Field} from "../../UtilityBar/widget/Field";
import {initProject} from "@src/editor/service";
import {Widget} from "../../UtilityBar/widget/Widget";
import {ScopeProvidor, useEditorContext} from "@src/editor/context";

i18next.addResourceBundle("en", "editor", {InitTool: en}, true, true);

export function InitUtility(): JSX.Element {
    const {storage} = useEditorContext();

    function projectCreate(event: SubmitEvent): void {
        event.preventDefault();

        const form = event.target as HTMLFormElement;
        const formData = new FormData(form);
        form.reset();

        const name = String(formData.get("name"));
        const width = Number(formData.get("width"));
        const height = Number(formData.get("height"));

        initProject(storage, {name, width, height});
    }

    return (
        <ScopeProvidor value="InitUtility">
            <Widget title="Init">
                <form
                    class={styles.InitTool}
                    onSubmit={projectCreate}
                >
                    <Field
                        label={
                            i18next.t(
                                "editor:InitTool.nameField",
                                {postProcess: ["capitalize"]}
                            )
                        }
                        name="name"
                        type="text"
                        required
                    />
                    <Field
                        label={
                            i18next.t(
                                "editor:InitTool.width",
                                {postProcess: ["capitalize"]}
                            )
                        }
                        name="width"
                        type="number"
                        required
                    />
                    <Field
                        label={
                            i18next.t(
                                "editor:InitTool.height",
                                {postProcess: ["capitalize"]}
                            )
                        }
                        name="height"
                        type="number"
                        required
                    />
                    <input
                        type="submit"
                        value={i18next.t(
                            "editor:InitTool.create",
                            {postprocess: ["capitalize"]}
                        )}
                    />
                </form>
            </Widget>
        </ScopeProvidor>
    );
}
