// src/feature/toolkit/view/Button/Button.tsx
import {Button as Prototype} from "@shared/view";
import * as styles from "./Button.module.scss";

type Props = {
    label?: string;
    icon?: string;
    pressed?: boolean;
    onClick?: (event?: MouseEvent) => void;
};

export function ToolViewButton(props: Props) {
    const classList = {
        button: styles.Button,
        pressed: styles.Pressed,
        icon: styles.Icon,
        label: styles.Label,
    };

    return (
        <Prototype
            label={props.label}
            icon={props.icon}
            pressed={props.pressed}
            classList={classList}
            onClick={props.onClick}
        />
    );
}

// src/shared/view/Button/Button.tsx
import * as styles from "./Button.module.scss";

import {JSX, Show} from "solid-js";

import {Icon} from "@shared/view";

type Props = {
    class?: string;
    pressed?: string;

    label?: string;
    tooltip?: string;
    icon?: string;
    name?: string;

    onClick?: (event?: MouseEvent) => void;
};

export function Button(props: Props): JSX.Element {
    return (
        <button
            classList={{
                [styles.Button]: true,
                [props.class ?? ""]: Boolean(props.class),
                [props.pressed ?? ""]: Boolean(props.pressed),
            }}
            title={props.tooltip}
            onClick={props.onClick}
            name={props.name}
        >
            <Show when={props.icon}>
                <Icon class={styles.Icon} svg={props.icon!}/>
            </Show>

            <Show when={props.label}>
                <label class={styles.Label}>{props.label}</label>
            </Show>
        </button>
    );
}
