// src/editor/view/utility/EntityNode.vue
<script setup lang="ts">
import LayerIconSvg from "@src/svg/small/layer.svg?raw";
import MarkerIconSvg from "@src/svg/small/marker.svg?raw";
import TrashIconSvg from "@src/svg/small/trash.svg?raw";
import TileIconSvg from "@src/svg/small/tile.svg?raw";
import FootnoteIconSvg from "@src/svg/small/footnote.svg?raw";

import TreeLeafItemIconSvg from "@src/svg/small/tree-leaf-item.svg?raw";
import TreeLeafOpenIconSvg from "@src/svg/small/tree-leaf-open.svg?raw";
import TreeLeafCloseIconSvg from "@src/svg/small/tree-leaf-close.svg?raw";

import type {Entity, Parent} from "@src/core/type";
import {Button, Icon} from "@src/core/view";
import {EntityKind} from "@src/core/enum";
import {useEditorContext} from "@src/editor/context";
import {computed, ref} from "vue";

const props = defineProps<{
	entityId: number;
	onClick?: (selected: unknown) => void;
}>();

const {storage, session, setSession} = useEditorContext();

const isExpanded = ref(false);

const entityMemo = computed(() => {
	const entity = storage.entity.select(props.entityId);
	if (!entity) throw new Error();
	return entity;
});

const isSelected = computed(() => {
	return session.selected?.id == props.entityId;
});

function expand(): void {
	isExpanded.value = !isExpanded.value;
}

function isParent(entity: Entity): entity is Entity & Parent {
	return "childIds" in entity;
}

function onSelect(): void {
	setSession({
		selected: entityMemo.value,
	});
}

const childrenMemo = computed(() => {
	// const entity = entityMemo.value;
	return undefined;
	// return isParent(entity)
	// 	? entity.childIds.map((id) => <EntityNode entityId={id}/>)
	// 	: undefined;
});

const icons: Record<string, {label: string; icon: string}> = {
	[EntityKind.Layer]: {
		label: "layer",
		icon: LayerIconSvg,
	},
	[EntityKind.Tile]: {
		label: "tile",
		icon: TileIconSvg,
	},
	[EntityKind.Marker]: {
		label: "marker",
		icon: MarkerIconSvg,
	},
	[EntityKind.Footnote]: {
		label: "footnote",
		icon: FootnoteIconSvg,
	},
};

const boop = icons[entityMemo.value.kind]
	|| {
		label: "undefined",
		icon: TrashIconSvg,
	};

const leafIconMemo = computed(() =>
	!childrenMemo.value
		? TreeLeafItemIconSvg
		: isExpanded.value
			? TreeLeafOpenIconSvg
			: TreeLeafCloseIconSvg
);
</script>

<template>
<div
	class="Node"
	:class="{
		'Selected': isSelected,
		'Expanded': isExpanded,
	}"
>
	<div
		class="Head"
		@click="onSelect"
	>
		<Button
			class="Icon"
			:icon="leafIconMemo"
			@click="expand"
		/>
		<Icon
			class="Icon"
			:svg="boop.icon"
		/>
		{{ boop.label }} (id {{ entityMemo.id }})
	</div>
	<div class="Body">
		{{ childrenMemo }}
	</div>
</div>
</template>

<style lang="scss">
.Node {
	pointer-events: none;
	display: inline;

	.Head {
		width: fit-content;
		display: flex;
		flex-direction: row;
		flex-wrap: nowrap;
		white-space: pre;
		gap: 8px;
		align-items: center;
		cursor: pointer;

		margin-top: 4px;

		padding: 2px;
		pointer-events: auto;

		.Icon {
			width: 16px;
			height: 16px;
		}
	}

	&.Selected>.Head {
		color: red;
	}

	&.Expanded>.Body {
		display: flex;
	}

	.Body {
		display: none;
		flex-direction: column;
		width: fit-content;
		padding-left: 24px;
	}

}
</style>

// src/feature/toolkit/view/EntityNode/EntityNode.tsx
import * as styles from "./EntityNode.module.scss";
import LayerIconSvg from "@res/svg/small/layer.svg";
import MarkerIconSvg from "@res/svg/small/marker.svg";
import TrashIconSvg from "@res/svg/small/trash.svg";
import TileIconSvg from "@res/svg/small/tile.svg";
import FootnoteIconSvg from "@res/svg/small/footnote.svg";

import TreeLeafItemIconSvg from "@res/svg/small/tree-leaf-item.svg";
import TreeLeafOpenIconSvg from "@res/svg/small/tree-leaf-open.svg";
import TreeLeafCloseIconSvg from "@res/svg/small/tree-leaf-close.svg";

import {JSXElement, createMemo, createSignal} from "solid-js";
import {useStoreContext} from "@feature/store/context";
import {Entity, Parent} from "@feature/entity/type";
import {Button, Icon} from "@shared/view";
import {ENTITY_TYPE} from "@feature/entity/enum";
import {useEditorContext} from "@feature/editor/context";

type Props = {
    entityId: number;
    onClick?: (selected: unknown) => void;
};

export function EntityNode(props: Props): JSXElement {
    const storeContext = useStoreContext();
    const editorContext = useEditorContext();

    const [isExpanded, setExpanded] = createSignal(false);

    const entityMemo = createMemo(() => {
        const entity = storeContext.store.entity.select(props.entityId);
        if (!entity) throw new Error();
        return entity;
    });

    const isSelected = createMemo(() => {
        return editorContext.state.selected?.id == props.entityId;
    });

    function expand(): void {
        setExpanded(!isExpanded());
    }

    function isParent(entity: Entity): entity is Parent {
        return "childIds" in entity;
    }

    function onSelect(): void {
        editorContext.setState({
            selected: entityMemo(),
        });
    }

    const childrenMemo = createMemo(() => {
        const entity = entityMemo();
        return isParent(entity)
            ? entity.childIds.map((id) => <EntityNode entityId={id}/>)
            : undefined;
    });

    const icons = {
        [ENTITY_TYPE.MARKER]: {
            label: "marker",
            icon: MarkerIconSvg,
        },
        [ENTITY_TYPE.LAYER]: {
            label: "layer",
            icon: LayerIconSvg,
        },
        [ENTITY_TYPE.TILE]: {
            label: "tile",
            icon: TileIconSvg,
        },
        [ENTITY_TYPE.FOOTNOTE]: {
            label: "footnote",
            icon: FootnoteIconSvg,
        },
    };

    const boop = icons[entityMemo().entityTypeId] || {
        label: "undefined",
        icon: TrashIconSvg,
    };

    const leafIconMemo = createMemo(() =>
        !childrenMemo()
            ? TreeLeafItemIconSvg
            : isExpanded()
                ? TreeLeafOpenIconSvg
                : TreeLeafCloseIconSvg
    );

    return (
        <div
            class={styles.Node}
            classList={{
                [styles.Selected]: isSelected(),
                [styles.Expanded]: isExpanded(),
            }}
        >
            <div class={styles.Head} onClick={onSelect}>
                <Button
                    classList={{icon: styles.Icon}}
                    icon={leafIconMemo()}
                    onClick={expand}
                />
                <Icon class={styles.Icon} svg={boop.icon}/>
                {boop.label} (id {entityMemo().id})
            </div>
            <div class={styles.Body}>
                {childrenMemo()}
            </div>
        </div>
    );
}
