// src/editor/view/utility/ExploreUtility.vue
<script setup lang="ts">
import {Widget} from "@src/editor/view/UtilityBar";
import {useScopeContext} from "@src/editor/context";
// import {EntityNode} from "./view";

useScopeContext("ExploreUtility");
</script>

<template>
<Widget title="Explore">
	<div class="Explorer">
		<!-- <EntityNode entityId={1}/> -->
	</div>
</Widget>
</template>

<style lang="scss">
.Explorer {
	overflow-y: scroll;
	overflow-x: scroll;
	pointer-events: none;
}
</style>

// src/editor/widget/utility/ExploreUtility/ExploreUtility.tsx
import * as styles from "./ExploreUtility.module.scss";
import {JSXElement} from "solid-js";
import {Widget} from "@src/editor/widget/UtilityBar/widget";
import {ScopeProvidor} from "@src/editor/context";
// import {EntityNode} from "./widget";

export function ExploreUtility(): JSXElement {
    return (
        <ScopeProvidor value="ExploreUtility">
            <Widget title="Explore">
                <div class="explorer" classList={{[styles.Explorer]: true}}>
                    {/* <EntityNode entityId={1}/> */}
                </div>
            </Widget>
        </ScopeProvidor>
    );
}
