// src/editor/widget/UtilityBar/widget/Section/Section.tsx
import {useScopeContext} from "@src/editor/context";
import * as styles from "./Section.module.scss";
import {JSX, children, createSignal} from "solid-js";

type Config = {
    collapsed: boolean;
};

type Props = {
    children: JSX.Element | JSX.Element[];
    title: string;
    class?: string;
};

export function Section(props: Props): JSX.Element {
    const {data, setData} = useScopeContext<Config>();

    const [collapsed, setCollapsed] = createSignal(data().collapsed);

    const childs = children(() => props.children);

    function toggleCollapsed() {
        setCollapsed(!collapsed());
        setData({collapsed: collapsed()});
    }

    return (
        <div
            class={styles.Section}
            classList={{
                [styles.Expand]: collapsed(),
            }}
        >
            <div
                class={styles.Header}
                onClick={toggleCollapsed}
            >
                <div class={styles.Title}>
                    {props.title}
                </div>
                <div
                    class={styles.Expand}
                >
                    {collapsed() ? "-" : "+"}
                </div>
            </div>
            <div
                class={styles.Content}
                classList={{
                    [props.class || ""]: Boolean(props.class),
                }}
            >
                {childs()}
            </div>
        </div>
    );
}

// src/editor/view/utility-bar/Section.vue
<script setup lang="ts">
import {useScopeContext} from "@src/editor/context";

const props = defineProps<{
	title: string;
	className?: string;
}>();

const scope = useScopeContext<{collapsed: boolean}>();
if (!scope.data.collapsed) scope.data.collapsed = false;

function toggleCollapsed(): void {
	scope.data.collapsed = !scope.data.collapsed;
}
</script>

<template>
<div
	class="Section"
	:class="{'Expand': scope.data.collapsed}"
>
	<div
		class="Header"
		@click="toggleCollapsed"
	>
		<div class="Title">
			{{ props.title }}
		</div>
		<div class="Expand">
			{{ scope.data.collapsed ? "-" : "+" }}
		</div>
	</div>
	<div :class="['Content', props.className]">
		<slot />
	</div>
</div>
</template>

<style lang="scss" scoped>
.Section {
    >.Header {
        display: flex;
        justify-content: space-between;

        >.Title {
            font-weight: bold;
        }
    }

    >.Content {
        padding: 8px;
        display: none;
    }

    &.Expand>.Content {
        display: block;
    }
}
</style>
